// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGYLiItceDF_aMH8Ar83YQjGVFW3_4wHs',
    appId: '1:291172457830:web:55d38d81af1db2a5b4fca7',
    messagingSenderId: '291172457830',
    projectId: 'evently-6540f',
    authDomain: 'evently-6540f.firebaseapp.com',
    storageBucket: 'evently-6540f.firebasestorage.app',
    measurementId: 'G-Z73WQRYFDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8mk8jFWnWTqx9RCDFBHh0C5bksvEt40',
    appId: '1:291172457830:android:0146aee4d2efd12ab4fca7',
    messagingSenderId: '291172457830',
    projectId: 'evently-6540f',
    storageBucket: 'evently-6540f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQGTM4kg3BdO3dce2A4lDcVHhl0N2yJrA',
    appId: '1:291172457830:ios:2609963a020b5c49b4fca7',
    messagingSenderId: '291172457830',
    projectId: 'evently-6540f',
    storageBucket: 'evently-6540f.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQGTM4kg3BdO3dce2A4lDcVHhl0N2yJrA',
    appId: '1:291172457830:ios:2609963a020b5c49b4fca7',
    messagingSenderId: '291172457830',
    projectId: 'evently-6540f',
    storageBucket: 'evently-6540f.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGYLiItceDF_aMH8Ar83YQjGVFW3_4wHs',
    appId: '1:291172457830:web:5f1b7de8ef19f4efb4fca7',
    messagingSenderId: '291172457830',
    projectId: 'evently-6540f',
    authDomain: 'evently-6540f.firebaseapp.com',
    storageBucket: 'evently-6540f.firebasestorage.app',
    measurementId: 'G-TVWDZLRXCG',
  );

}